version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: dev-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 8f7d2c1e
      MONGO_INITDB_DATABASE: bookmark
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
