version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: bookmark-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 8f7d2c1e
      MONGO_INITDB_DATABASE: bookmark
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: bookmark-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass 123456
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
