version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: bookmark-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: VN8m$f7x@yn&!cMGF&gi%j
      MONGO_INITDB_DATABASE: bookmark
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: bookmark-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ee$p&@kjzrkh7hg*kst9w#
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
