export enum CodeEnums {
  // 通用错误码
  COMMON_SUCCESSFUL = 'SUCCESSFUL',
  COMMON_FAILED = 'FAILED',
  COMMON_NOT_LOGIN = 'NOT_LOGIN',
  COMMON_PARAMS_ERROR = 'PARAMS_ERROR',
  COMMON_SERVER_ERROR = 'SERVER_ERROR',
  COMMON_VALIDATION_ERROR = 'VALIDATION_ERROR',
  COMMON_BAD_REQUEST = 'BAD_REQUEST',

  // Mongoose 相关错误码
  MONGOOSE_CAST_ERROR = 'MONGOOSE_CAST_ERROR',
  MONGOOSE_VALIDATION_ERROR = 'MONGOOSE_VALIDATION_ERROR',
  MONGOOSE_NOT_FOUND = 'MONGOOSE_NOT_FOUND',
  MONGOOSE_ERROR = 'MONGOOSE_ERROR',

  // 认证相关错误码
  AUTH_PASSWORD_ERROR = 'AUTH_PASSWORD_ERROR',
  AUTH_EMAIL_NOT_FOUND = 'AUTH_EMAIL_NOT_FOUND',
  AUTH_EMAIL_CODE_ERROR = 'AUTH_EMAIL_CODE_ERROR',
  AUTH_EMAIL_CODE_EXIST = 'AUTH_EMAIL_CODE_EXIST',
  AUTH_EMAIL_CODE_TOO_FREQUENT = 'AUTH_EMAIL_CODE_TOO_FREQUENT',
  AUTH_NOT_FOUND_TOKEN = 'AUTH_NOT_FOUND_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_ERROR = 'AUTH_TOKEN_ERROR',
  AUTH_FAILED = 'AUTH_FAILED',

  // 用户相关错误码
  USER_CREATE_ERROR = 'USER_CREATE_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // 书签相关错误码
  BOOKMARK_NOT_FOUND = 'BOOKMARK_NOT_FOUND',
  BOOKMARK_ALREADY_EXISTS = 'BOOKMARK_ALREADY_EXISTS',
  BOOKMARK_CREATE_ERROR = 'BOOKMARK_CREATE_ERROR',
  BOOKMARK_UPDATE_ERROR = 'BOOKMARK_UPDATE_ERROR',
  BOOKMARK_DELETE_ERROR = 'BOOKMARK_DELETE_ERROR',

  // 书签标签相关错误码
  BOOKMARK_TAG_NOT_FOUND = 'BOOKMARK_TAG_NOT_FOUND',
  BOOKMARK_TAG_ALREADY_EXISTS = 'BOOKMARK_TAG_ALREADY_EXISTS',
  BOOKMARK_TAG_CREATE_ERROR = 'BOOKMARK_TAG_CREATE_ERROR',
  BOOKMARK_TAG_UPDATE_ERROR = 'BOOKMARK_TAG_UPDATE_ERROR',
  BOOKMARK_TAG_DELETE_ERROR = 'BOOKMARK_TAG_DELETE_ERROR',

  // 书签分类相关错误码
  BOOKMARK_CATEGORY_NOT_FOUND = 'BOOKMARK_CATEGORY_NOT_FOUND',
  BOOKMARK_CATEGORY_ALREADY_EXISTS = 'BOOKMARK_CATEGORY_ALREADY_EXISTS',
  BOOKMARK_CATEGORY_CREATE_ERROR = 'BOOKMARK_CATEGORY_CREATE_ERROR',
  BOOKMARK_CATEGORY_UPDATE_ERROR = 'BOOKMARK_CATEGORY_UPDATE_ERROR',
  BOOKMARK_CATEGORY_DELETE_ERROR = 'BOOKMARK_CATEGORY_DELETE_ERROR',
}
